sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev . -t pranavchandran/docker-react
script:
  - docker run pranavchandran/docker-react npm run test -- --coverage 
